twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        '%kernel.project_dir%/templates/demos/live_memory': ~

when@test:
    twig:
        strict_variables: true
