name: Symfony UX

on: [push, pull_request]

jobs:
    coding-style-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  tools: php-cs-fixer, cs2pr
            - name: php-cs-fixer
              run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

    coding-style-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn
            - run: yarn check-lint
            - run: yarn check-format

    js-dist-current:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn && yarn build
            - name: Check if js dist files are current
              id: changes
              uses: UnicornGlobal/has-changes-action@v1.0.11

            - name: Ensure no changes
              if: steps.changes.outputs.changed == 1
              run: |
                echo "JS dist files need to be rebuilt"
                exit 1

    tests-php-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.2'

            - name: Chartjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Chartjs
                  dependency-versions: lowest
            - name: Chartjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Chartjs

            - name: Cropperjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Cropperjs
                  dependency-versions: lowest
            - name: Cropperjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Cropperjs

            - name: Dropzone Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Dropzone
                  dependency-versions: lowest
            - name: Dropzone Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Dropzone

            - name: LazyImage Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LazyImage
                  dependency-versions: lowest
            - name: LazyImage Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/LazyImage

    tests-php8-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'

            - name: TwigComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/TwigComponent
                  dependency-versions: lowest
            - name: TwigComponent Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/TwigComponent

            - name: LiveComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LiveComponent
                  dependency-versions: lowest
            - name: LiveComponent Tests
              working-directory: src/LiveComponent
              run: php vendor/bin/simple-phpunit

    tests-php-high-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - run: php .github/build-packages.php

            - name: Chartjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Chartjs
            - name: Chartjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Chartjs

            - name: Cropperjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Cropperjs
            - name: Cropperjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Cropperjs

            - name: Dropzone Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Dropzone
            - name: Dropzone Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Dropzone

            - name: LazyImage Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LazyImage
            - name: LazyImage Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/LazyImage

            - name: TwigComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/TwigComponent
            - name: TwigComponent Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/TwigComponent

            - name: LiveComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LiveComponent
            - name: LiveComponent Tests
              working-directory: src/LiveComponent
              run: php vendor/bin/simple-phpunit

    tests-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn
            - run: yarn test
