name: Symfony UX

on:
    push:
    pull_request:

jobs:
    coding-style-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - uses: ramsey/composer-install@v2
            - name: php-cs-fixer
              run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

    coding-style-js:
        name: JavaScript Coding Style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile
            - run: yarn check-lint
            - run: yarn check-format

    js-dist-current:
        name: Check for UnBuilt JS Dist Files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile && yarn build
            - name: Check if js dist files are current
              id: changes
              run: |
                echo "STATUS=$(git status --porcelain)" >> $GITHUB_OUTPUT

            - name: No changes found
              if: steps.changes.outputs.STATUS == ''
              run: |
                echo "git status is clean"
            - name: Changes were found
              if: steps.changes.outputs.STATUS != ''
              run: |
                echo "JS dist files need to be rebuilt"
                echo "${{ steps.changes.outputs.STATUS }}"
                exit 1

    tests-php-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.2'

            - name: Chartjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Chartjs
                  dependency-versions: lowest
            - name: Chartjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Chartjs

            - name: Cropperjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Cropperjs
                  dependency-versions: lowest
            - name: Cropperjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Cropperjs

            - name: Dropzone Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Dropzone
                  dependency-versions: lowest
            - name: Dropzone Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Dropzone

            - name: LazyImage Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LazyImage
                  dependency-versions: lowest
            - name: LazyImage Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/LazyImage

            - name: React Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/React
                  dependency-versions: lowest
            - name: React Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/React

            - name: Svelte Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Svelte
                  dependency-versions: lowest
            - name: Svelte Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Svelte

    tests-php8-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'

            - name: TwigComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/TwigComponent
                  dependency-versions: lowest
            - name: TwigComponent Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/TwigComponent

            - name: LiveComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LiveComponent
                  dependency-versions: lowest
            - name: LiveComponent Tests
              working-directory: src/LiveComponent
              run: php vendor/bin/simple-phpunit

            - name: Autocomplete Dependencies
              uses: ramsey/composer-install@v2
              with:
                working-directory: src/Autocomplete
                dependency-versions: lowest
            - name: Autocomplete Tests
              working-directory: src/Autocomplete
              run: php vendor/bin/simple-phpunit

    tests-php-high-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - run: php .github/build-packages.php

            - name: Chartjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Chartjs
            - name: Chartjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Chartjs

            - name: Cropperjs Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Cropperjs
            - name: Cropperjs Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Cropperjs

            - name: Dropzone Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Dropzone
            - name: Dropzone Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/Dropzone

            - name: LazyImage Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LazyImage
            - name: LazyImage Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/LazyImage

            - name: TwigComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/TwigComponent
            - name: TwigComponent Tests
              run: php vendor/bin/simple-phpunit
              working-directory: src/TwigComponent

            - name: LiveComponent Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/LiveComponent
            - name: LiveComponent Tests
              working-directory: src/LiveComponent
              run: php vendor/bin/simple-phpunit

            - name: React Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/React
            - name: React Tests
              working-directory: src/React
              run: php vendor/bin/simple-phpunit

            - name: Autocomplete Dependencies
              uses: ramsey/composer-install@v2
              with:
                working-directory: src/Autocomplete
            - name: Autocomplete Tests
              working-directory: src/Autocomplete
              run: php vendor/bin/simple-phpunit

            - name: Svelte Dependencies
              uses: ramsey/composer-install@v2
              with:
                working-directory: src/Svelte
            - name: Svelte Tests
              working-directory: src/Svelte
              run: php vendor/bin/simple-phpunit

    tests-php81-high-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
            - run: php .github/build-packages.php

            - name: Notify Dependencies
              uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Notify
            - name: Notify Tests
              working-directory: src/Notify
              run: php vendor/bin/simple-phpunit

    tests-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile
            - run: yarn test
