name: Symfony UX Turbo

on:
    push:
    pull_request:

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  extensions: zip

            - uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Turbo

            - name: Install PHPUnit dependencies
              working-directory: src/Turbo
              run: vendor/bin/simple-phpunit --version

            - name: PHPStan
              working-directory: src/Turbo
              run: vendor/bin/phpstan analyse --no-progress

    tests-php-high-deps:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2', '7.3', '7.4', '8.0']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} Test on ubuntu-latest

        services:
            mercure:
                image: dunglas/mercure
                env:
                    SERVER_NAME: :3000
                    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
                    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
                    MERCURE_EXTRA_DIRECTIVES: |
                        anonymous
                        cors_origins *
                ports:
                    - 3000:3000

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: zip, pdo_sqlite

            - uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Turbo

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install JavaScript dependencies
              working-directory: src/Turbo/Tests/app
              run: yarn install

            - name: Build JavaScript
              working-directory: src/Turbo/Tests/app
              run: yarn build

            - name: Create DB
              working-directory: src/Turbo/Tests/app
              run: php public/index.php doctrine:schema:create

            - name: Run tests
              working-directory: src/Turbo
              env:
                  SYMFONY_DEPRECATIONS_HELPER: max[direct]=0
              run: vendor/bin/simple-phpunit

    tests-php-low-deps:
        runs-on: ubuntu-latest
        name: PHP 8.0 (lowest) Test on ubuntu-latest

        services:
            mercure:
                image: dunglas/mercure
                env:
                    SERVER_NAME: :3000
                    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
                    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
                    MERCURE_EXTRA_DIRECTIVES: |
                        anonymous
                        cors_origins *
                ports:
                    - 3000:3000

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  extensions: zip, pdo_sqlite

            - uses: ramsey/composer-install@v2
              with:
                  working-directory: src/Turbo
                  dependency-versions: lowest

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install JavaScript dependencies
              working-directory: src/Turbo/Tests/app
              run: yarn install

            - name: Build JavaScript
              working-directory: src/Turbo/Tests/app
              run: yarn build

            - name: Create DB
              working-directory: src/Turbo/Tests/app
              run: php public/index.php doctrine:schema:create

            - name: Run tests
              working-directory: src/Turbo
              env:
                  SYMFONY_DEPRECATIONS_HELPER: max[total]=9223372036854775807 # PHP_INT_MAX
              run: vendor/bin/simple-phpunit
