name: ux.symfony.com

on:
    push:
        paths:
            - 'ux.symfony.com/**'
    pull_request:
        paths:
            - 'ux.symfony.com/**'

jobs:
    tests:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: ux.symfony.com

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.1

            - name: Install dependencies
              uses: ramsey/composer-install@v2
              with:
                working-directory: ux.symfony.com

            - name: Importmap dependencies
              run: php bin/console importmap:install

            - name: Build Sass assets
              run: php bin/console sass:build

            - name: Tests
              run: vendor/bin/phpunit
